spring:

  mail:
    host: localhost
    port: 1025
    username: francisco
    password: 1234567890
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.ffreitas.ecommerce.kafka.order.OrderConfirmation,paymentNotificationRequest:com.ffreitas.ecommerce.kafka.payment.PaymentConfirmation

  data:
    mongodb:
      username: francisco
      password: 1234567890
      host: localhost
      port: 27017
      database: notificationdb
      authentication-database: admin
      uri: mongodb://francisco:1234567890@localhost/notificationdb?ssl=false&authSource=admin

server:
  port: 8040

application:
  kafka:
    payment-topic-name: payment-topic
    order-topic-name: order-topic

  email:
    emailFrom: example@yopmail.com