spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order
    username: francisco
    password: 1234567890

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

server:
  port: 8070

application:
  config:
    customer-baseurl: http://localhost:8222/api/v1/customers
    payment-baseurl: http://localhost:8222/api/v1/payments
    product-baseurl: http://localhost:8222/api/v1/products